name: CI
run-name: r-type actions
on:
  push:
  pull_request:
jobs:
  build-rtype:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        uses: DeterminateSystems/nix-installer-action@main

      - run: |
          sudo apt-get update
          nix build .

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ccache
          key: ccache-${{ runner.os }}-${{ hashFiles('**/*.c', '**/*.cpp', '**/*.h', '**/*.hpp', '**/CMakeLists.txt') }}
          restore-keys: |
            ccache-${{ runner.os }}

      - name: Configure
        run: cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache \
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        run: cmake --build build --parallel

      - name: Execute
        run: ./bin/r-type_server

      - name: ccache stats
        run: ccache -s || true
